# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  # server:

  #   runs-on: self-hosted

  #   strategy:
  #     matrix:
  #       node-version: [18.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm install
  #   - run: pwd
  #   - run: pm2 stop 0 
  #   - run: npm install --prefix server
  #   - run: pm2 restart 0

  client:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./client
      # When application is successfully tested and build has been generated
      # Then we can start with deployment
    # needs: server
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - run: npm install
    - run: pwd
    - run: pm2 stop
    - run: pm2 restart 0
